DELETE FROM schedules;

SELECT id INTO @studio_id FROM studios WHERE name = "立川校";
SELECT id INTO @room_id FROM rooms WHERE studio_rooms = @studio_id AND name = "A";

INSERT INTO schedules (day_of_week, start_time, end_time, room_schedules, create_time, update_time) VALUE (1, "15:30", "16:40",  @room_id, now(), now()),
                                                                                                          (1, "16:45", "17:55",  @room_id, now(), now()),
                                                                                                          (1, "18:00", "19:10",  @room_id, now(), now()),
                                                                                                          (1, "19:15", "20:25",  @room_id, now(), now()),
                                                                                                          (1, "20:30", "21:40",  @room_id, now(), now()),
                                                                                                          (1, "21:45", "22:55",  @room_id, now(), now()),
                                                                                                          (2, "15:30", "16:40",  @room_id, now(), now()),
                                                                                                          (2, "16:45", "17:55",  @room_id, now(), now()),
                                                                                                          (2, "18:00", "19:10",  @room_id, now(), now()),
                                                                                                          (2, "19:15", "20:25",  @room_id, now(), now()),
                                                                                                          (2, "20:30", "21:40",  @room_id, now(), now()),
                                                                                                          (2, "21:45", "22:55",  @room_id, now(), now()),
                                                                                                          (3, "15:30", "16:40",  @room_id, now(), now()),
                                                                                                          (3, "16:45", "17:55",  @room_id, now(), now()),
                                                                                                          (3, "18:00", "19:10",  @room_id, now(), now()),
                                                                                                          (3, "19:15", "20:25",  @room_id, now(), now()),
                                                                                                          (3, "20:30", "21:40",  @room_id, now(), now()),
                                                                                                          (3, "21:45", "22:55",  @room_id, now(), now()),
                                                                                                          (4, "15:30", "16:40",  @room_id, now(), now()),
                                                                                                          (4, "16:45", "17:55",  @room_id, now(), now()),
                                                                                                          (4, "18:00", "19:10",  @room_id, now(), now()),
                                                                                                          (4, "19:15", "20:25",  @room_id, now(), now()),
                                                                                                          (4, "20:30", "21:40",  @room_id, now(), now()),
                                                                                                          (4, "21:45", "22:55",  @room_id, now(), now()),
                                                                                                          (5, "15:30", "16:40",  @room_id, now(), now()),
                                                                                                          (5, "16:45", "17:55",  @room_id, now(), now()),
                                                                                                          (5, "18:00", "19:10",  @room_id, now(), now()),
                                                                                                          (5, "19:15", "20:25",  @room_id, now(), now()),
                                                                                                          (5, "20:30", "21:40",  @room_id, now(), now()),
                                                                                                          (5, "21:45", "22:55",  @room_id, now(), now()),
                                                                                                          (6, "13:00", "14:00",  @room_id, now(), now()),
                                                                                                          (6, "14:15", "15:25",  @room_id, now(), now()),
                                                                                                          (6, "15:30", "16:40",  @room_id, now(), now()),
                                                                                                          (6, "16:45", "17:55",  @room_id, now(), now()),
                                                                                                          (6, "18:00", "19:10",  @room_id, now(), now()),
                                                                                                          (6, "19:15", "20:25",  @room_id, now(), now()),
                                                                                                          (6, "20:30", "21:40",  @room_id, now(), now()),
                                                                                                          (6, "21:45", "22:55",  @room_id, now(), now()),
                                                                                                          (7, "13:00", "14:00",  @room_id, now(), now()),
                                                                                                          (7, "14:15", "15:25",  @room_id, now(), now()),
                                                                                                          (7, "15:30", "16:40",  @room_id, now(), now()),
                                                                                                          (7, "16:45", "17:55",  @room_id, now(), now()),
                                                                                                          (7, "18:00", "19:10",  @room_id, now(), now()),
                                                                                                          (7, "19:15", "20:25",  @room_id, now(), now()),
                                                                                                          (7, "20:30", "21:40",  @room_id, now(), now()),
                                                                                                          (7, "21:45", "22:55",  @room_id, now(), now());