steps:
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ["install"]
    dir: "frontend"
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ["run", "build"]
    dir: "frontend"

artifacts:
  objects:
    location: "gs://landin.tk"
    paths: ["frontend/build/*"]
