version: "3.9"

services:
  frontend:
    build:
      context: frontend
      dockerfile: '.devcontainer/Dockerfile'
      # target: dev
    command: sleep infinity
    depends_on:
      - backend
    env_file: .env
    volumes:
      - ./frontend:/usr/local/src
      - frontend-extensions:/root/.vscode-server/extensions
      - node_modules:/usr/local/src/node_modules
  backend:
    build:
      context: backend
      dockerfile: '.devcontainer/Dockerfile'
      # target: dev
    command: sleep infinity
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - ./backend:/go/src/app
      - backend-extensions:/root/.vscode-server/extensions
    ports:
      - "3000:3000"
  mysql:
    platform: linux/x86_64
    image: mysql:8
    env_file:
      - .env
    command: mysqld --default_authentication_plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  frontend-extensions:
  node_modules:
  backend-extensions:
  mysql-data:
