version: "3.9"

services:
  go:
    build:
      context: .
      dockerfile: '.devcontainer/Dockerfile'
      # target: dev
    command: sleep infinity
    env_file: .env
    volumes:
      - .:/app
      - go-extensions:/root/.vscode-server/extensions
    ports:
      - "3000:3000"
      - "2345:2345"
  mysql:
    platform: linux/x86_64
    image: mysql:8
    env_file:
      - .env
    command: mysqld --default_authentication_plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
  go-extensions:
