steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [
            'build',
            '-f',
            'backend/Dockerfile',
            '-t',
            'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/docker-repo/backend:${SHORT_SHA}',
            './backend'
          ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'push',
            'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/docker-repo/backend:${SHORT_SHA}'
          ]
