steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t',
           'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/backend/myimage',
           '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/backend/myimage']
