// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/matsuokashuhei/landin/ent/class"
	"github.com/matsuokashuhei/landin/ent/instructor"
	"github.com/matsuokashuhei/landin/ent/predicate"
	"github.com/matsuokashuhei/landin/ent/schedule"
)

// ClassUpdate is the builder for updating Class entities.
type ClassUpdate struct {
	config
	hooks    []Hook
	mutation *ClassMutation
}

// Where appends a list predicates to the ClassUpdate builder.
func (cu *ClassUpdate) Where(ps ...predicate.Class) *ClassUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUpdateTime sets the "update_time" field.
func (cu *ClassUpdate) SetUpdateTime(t time.Time) *ClassUpdate {
	cu.mutation.SetUpdateTime(t)
	return cu
}

// SetStartDate sets the "start_date" field.
func (cu *ClassUpdate) SetStartDate(t time.Time) *ClassUpdate {
	cu.mutation.SetStartDate(t)
	return cu
}

// SetEndDate sets the "end_date" field.
func (cu *ClassUpdate) SetEndDate(t time.Time) *ClassUpdate {
	cu.mutation.SetEndDate(t)
	return cu
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (cu *ClassUpdate) SetNillableEndDate(t *time.Time) *ClassUpdate {
	if t != nil {
		cu.SetEndDate(*t)
	}
	return cu
}

// ClearEndDate clears the value of the "end_date" field.
func (cu *ClassUpdate) ClearEndDate() *ClassUpdate {
	cu.mutation.ClearEndDate()
	return cu
}

// SetScueduleID sets the "scuedule" edge to the Schedule entity by ID.
func (cu *ClassUpdate) SetScueduleID(id int) *ClassUpdate {
	cu.mutation.SetScueduleID(id)
	return cu
}

// SetNillableScueduleID sets the "scuedule" edge to the Schedule entity by ID if the given value is not nil.
func (cu *ClassUpdate) SetNillableScueduleID(id *int) *ClassUpdate {
	if id != nil {
		cu = cu.SetScueduleID(*id)
	}
	return cu
}

// SetScuedule sets the "scuedule" edge to the Schedule entity.
func (cu *ClassUpdate) SetScuedule(s *Schedule) *ClassUpdate {
	return cu.SetScueduleID(s.ID)
}

// SetInstructorID sets the "instructor" edge to the Instructor entity by ID.
func (cu *ClassUpdate) SetInstructorID(id int) *ClassUpdate {
	cu.mutation.SetInstructorID(id)
	return cu
}

// SetNillableInstructorID sets the "instructor" edge to the Instructor entity by ID if the given value is not nil.
func (cu *ClassUpdate) SetNillableInstructorID(id *int) *ClassUpdate {
	if id != nil {
		cu = cu.SetInstructorID(*id)
	}
	return cu
}

// SetInstructor sets the "instructor" edge to the Instructor entity.
func (cu *ClassUpdate) SetInstructor(i *Instructor) *ClassUpdate {
	return cu.SetInstructorID(i.ID)
}

// Mutation returns the ClassMutation object of the builder.
func (cu *ClassUpdate) Mutation() *ClassMutation {
	return cu.mutation
}

// ClearScuedule clears the "scuedule" edge to the Schedule entity.
func (cu *ClassUpdate) ClearScuedule() *ClassUpdate {
	cu.mutation.ClearScuedule()
	return cu
}

// ClearInstructor clears the "instructor" edge to the Instructor entity.
func (cu *ClassUpdate) ClearInstructor() *ClassUpdate {
	cu.mutation.ClearInstructor()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ClassUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	cu.defaults()
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ClassMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ClassUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ClassUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ClassUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *ClassUpdate) defaults() {
	if _, ok := cu.mutation.UpdateTime(); !ok {
		v := class.UpdateDefaultUpdateTime()
		cu.mutation.SetUpdateTime(v)
	}
}

func (cu *ClassUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   class.Table,
			Columns: class.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: class.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: class.FieldUpdateTime,
		})
	}
	if value, ok := cu.mutation.StartDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: class.FieldStartDate,
		})
	}
	if value, ok := cu.mutation.EndDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: class.FieldEndDate,
		})
	}
	if cu.mutation.EndDateCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: class.FieldEndDate,
		})
	}
	if cu.mutation.ScueduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.ScueduleTable,
			Columns: []string{class.ScueduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: schedule.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ScueduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.ScueduleTable,
			Columns: []string{class.ScueduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: schedule.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.InstructorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.InstructorTable,
			Columns: []string{class.InstructorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: instructor.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.InstructorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.InstructorTable,
			Columns: []string{class.InstructorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: instructor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{class.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ClassUpdateOne is the builder for updating a single Class entity.
type ClassUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClassMutation
}

// SetUpdateTime sets the "update_time" field.
func (cuo *ClassUpdateOne) SetUpdateTime(t time.Time) *ClassUpdateOne {
	cuo.mutation.SetUpdateTime(t)
	return cuo
}

// SetStartDate sets the "start_date" field.
func (cuo *ClassUpdateOne) SetStartDate(t time.Time) *ClassUpdateOne {
	cuo.mutation.SetStartDate(t)
	return cuo
}

// SetEndDate sets the "end_date" field.
func (cuo *ClassUpdateOne) SetEndDate(t time.Time) *ClassUpdateOne {
	cuo.mutation.SetEndDate(t)
	return cuo
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (cuo *ClassUpdateOne) SetNillableEndDate(t *time.Time) *ClassUpdateOne {
	if t != nil {
		cuo.SetEndDate(*t)
	}
	return cuo
}

// ClearEndDate clears the value of the "end_date" field.
func (cuo *ClassUpdateOne) ClearEndDate() *ClassUpdateOne {
	cuo.mutation.ClearEndDate()
	return cuo
}

// SetScueduleID sets the "scuedule" edge to the Schedule entity by ID.
func (cuo *ClassUpdateOne) SetScueduleID(id int) *ClassUpdateOne {
	cuo.mutation.SetScueduleID(id)
	return cuo
}

// SetNillableScueduleID sets the "scuedule" edge to the Schedule entity by ID if the given value is not nil.
func (cuo *ClassUpdateOne) SetNillableScueduleID(id *int) *ClassUpdateOne {
	if id != nil {
		cuo = cuo.SetScueduleID(*id)
	}
	return cuo
}

// SetScuedule sets the "scuedule" edge to the Schedule entity.
func (cuo *ClassUpdateOne) SetScuedule(s *Schedule) *ClassUpdateOne {
	return cuo.SetScueduleID(s.ID)
}

// SetInstructorID sets the "instructor" edge to the Instructor entity by ID.
func (cuo *ClassUpdateOne) SetInstructorID(id int) *ClassUpdateOne {
	cuo.mutation.SetInstructorID(id)
	return cuo
}

// SetNillableInstructorID sets the "instructor" edge to the Instructor entity by ID if the given value is not nil.
func (cuo *ClassUpdateOne) SetNillableInstructorID(id *int) *ClassUpdateOne {
	if id != nil {
		cuo = cuo.SetInstructorID(*id)
	}
	return cuo
}

// SetInstructor sets the "instructor" edge to the Instructor entity.
func (cuo *ClassUpdateOne) SetInstructor(i *Instructor) *ClassUpdateOne {
	return cuo.SetInstructorID(i.ID)
}

// Mutation returns the ClassMutation object of the builder.
func (cuo *ClassUpdateOne) Mutation() *ClassMutation {
	return cuo.mutation
}

// ClearScuedule clears the "scuedule" edge to the Schedule entity.
func (cuo *ClassUpdateOne) ClearScuedule() *ClassUpdateOne {
	cuo.mutation.ClearScuedule()
	return cuo
}

// ClearInstructor clears the "instructor" edge to the Instructor entity.
func (cuo *ClassUpdateOne) ClearInstructor() *ClassUpdateOne {
	cuo.mutation.ClearInstructor()
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ClassUpdateOne) Select(field string, fields ...string) *ClassUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Class entity.
func (cuo *ClassUpdateOne) Save(ctx context.Context) (*Class, error) {
	var (
		err  error
		node *Class
	)
	cuo.defaults()
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ClassMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ClassUpdateOne) SaveX(ctx context.Context) *Class {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ClassUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ClassUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *ClassUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdateTime(); !ok {
		v := class.UpdateDefaultUpdateTime()
		cuo.mutation.SetUpdateTime(v)
	}
}

func (cuo *ClassUpdateOne) sqlSave(ctx context.Context) (_node *Class, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   class.Table,
			Columns: class.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: class.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Class.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, class.FieldID)
		for _, f := range fields {
			if !class.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != class.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: class.FieldUpdateTime,
		})
	}
	if value, ok := cuo.mutation.StartDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: class.FieldStartDate,
		})
	}
	if value, ok := cuo.mutation.EndDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: class.FieldEndDate,
		})
	}
	if cuo.mutation.EndDateCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: class.FieldEndDate,
		})
	}
	if cuo.mutation.ScueduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.ScueduleTable,
			Columns: []string{class.ScueduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: schedule.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ScueduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.ScueduleTable,
			Columns: []string{class.ScueduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: schedule.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.InstructorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.InstructorTable,
			Columns: []string{class.InstructorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: instructor.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.InstructorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.InstructorTable,
			Columns: []string{class.InstructorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: instructor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Class{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{class.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
