// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/matsuokashuhei/landin/internal/models"
)

type CreateInstructorInput struct {
	Name               string  `json:"name"`
	SyllabicCharacters string  `json:"syllabicCharacters"`
	Biography          *string `json:"biography"`
	PhoneNumber        *string `json:"phoneNumber"`
	Email              *string `json:"email"`
}

type CreateRoomInput struct {
	Name     string `json:"name"`
	Capacity uint   `json:"capacity"`
	StudioID uint   `json:"studioID"`
}

type CreateSchoolInput struct {
	Name string `json:"name"`
}

type CreateStudioInput struct {
	Name     string `json:"name"`
	Location string `json:"location"`
	SchoolID uint   `json:"schoolID"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CursorBasedPageInfo struct {
	StartCursor       uint `json:"startCursor"`
	EndCursor         uint `json:"endCursor"`
	HasNextPage       bool `json:"hasNextPage"`
	HasPreviciousPage bool `json:"hasPreviciousPage"`
}

type InstructorsConnection struct {
	Nodes    []*models.Instructor `json:"nodes"`
	PageInfo *OffsetBasedPageInfo `json:"pageInfo"`
}

type OffsetBasedPageInfo struct {
	CurrentPage uint `json:"currentPage"`
	TotalPage   uint `json:"totalPage"`
	TotalCount  uint `json:"totalCount"`
}

type SignUpInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateRoomInput struct {
	ID       uint    `json:"id"`
	Name     *string `json:"name"`
	Capacity uint    `json:"capacity"`
	StudioID *uint   `json:"studioID"`
}

type UpdateSchoolInput struct {
	ID   uint   `json:"id"`
	Name string `json:"name"`
}

type UpdateStudioInput struct {
	ID       uint    `json:"id"`
	Name     *string `json:"name"`
	Location string  `json:"location"`
	SchoolID *uint   `json:"schoolID"`
}
