apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: landin-slack-notifier
spec:
  notification:
    filter: build.status == Build.Status.SUCCESS
    delivery:
      webhookUrl:
        secretRef: slack-webhook-url
  secrets:
  - name: slack-webhook-url
    value: projects/874250046469/secrets/slack_webhook_url/versions/latest
